17 add request for actors to show actors objects not only ids
MaleryValery/movies pull request #26
Opened 2024-04-20 13:16 UTC by AndreevSV

Task done

2024-04-20 22:03 UTC, MaleryValery requested changes

2024-04-20 22:03 UTC, MaleryValery commented on movies/service.js
> +
все равно вложенность массива в массиве, но без лишних запросов
const constructNewMoviesArr = async (movies) => {
  if (!movies.length) return [];

  const actorIds = movies.map((movie) => movie.actors).flat();
  const actorsBD = await ActorModel.find({ _id: { $in: actorIds } });
  const actorsMap = new Map(actorsBD.map((actorsBD) => [actorsBD._id.toString(), actorsBD]));

  movies.forEach((movie) => {
    movie.actors = movie.actors.map((actor) => actorsMap.get(actor));
  });
  return movies;
};

2024-04-20 22:03 UTC, MaleryValery commented on movies/service.js
> +    const actorsArr = await constructActorsArr(ids);
const actorsArr = await ActorModel.find({ _id: { $in: ids } });

2024-04-21 08:21 UTC, AndreevSV commented on movies/service.js
> +    const actorsArr = await constructActorsArr(ids);
It's not allowed to make a direct request to DB from one model to another model. In this case use only methods of service from another object. Services talk just between each other and service can request only model that it was made for

2024-04-21 08:24 UTC, AndreevSV commented on movies/service.js
> +
Same answer like below. You are not allowed  to use direct request from one model to another model in service. You should use just another service.

2024-04-21 11:00 UTC, MaleryValery approved these changes

2024-04-21 11:24 UTC, merged